### ISSUE TITLE
Not working from Windows env 

### ISSUE THREAD

**Issue by soleanos** [claudiobizzotto/pyautogui-with-selenium#2]
Hello, 

Im actually trying to execute what you did in windows env but it doesnt work.. when i run the test docker exec command i got the following error : 

Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
IsADirectoryError: [Errno 21] Is a directory: '/home/seluser/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./d2utmpSQItDO", line 7, in <module>
    import pyautogui
  File "/home/seluser/.local/lib/python3.6/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/home/seluser/.local/lib/python3.6/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 103, in new_get_auth
    au = xauth.Xauthority()
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 21] Is a directory: '/home/seluser/.Xauthority'

Would you have a idea ? 

Thank you

**Comment by claudiobizzotto** [comment]
That Docker Compose file (`docker-compose.yaml`) will not work on Windows, not even if you run it from WSL (Windows Subsystem for Linux), because it assumes your operating system uses the X windowing system (it tries to mount a file that typically only exists on *nix systems).
