### ISSUE TITLE
Xauthority error

### ISSUE THREAD

**Issue by ucsky** [claudiobizzotto/pyautogui-with-selenium#4]
Hello,

Running, `docker exec selenium-chrome ilovemepaws`, I go this error:

```Traceback (most recent call last):
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
IsADirectoryError: [Errno 21] Is a directory: '/home/seluser/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ilovemepaws/ilovemepaws", line 7, in <module>
    import pyautogui
  File "/home/seluser/.local/lib/python3.6/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/home/seluser/.local/lib/python3.6/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 103, in new_get_auth
    au = xauth.Xauthority()
  File "/home/seluser/.local/lib/python3.6/site-packages/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 21] Is a directory: '/home/seluser/.Xauthority'
```

**Comment by mariliarosa4** [comment]
Same error

**Comment by giuseppegargiuolo** [comment]
Same error also for me.

When I run docker-compose up -d everything is fine.
My host operating system is Windows 10

**Comment by claudiobizzotto** [comment]
Docker and Docker Compose will work on Windows, but *how* they work is fundamentally different than how they do natively (on Linux). For example, there's no native X windowing system on Windows, and because I rely on that for the dockerized tests in this repository, it's natural that Windows users will see these errors. That being said, you can still use this repository, but without Docker.

In short: Windows users should stick with [plain Python](https://github.com/claudiobizzotto/pyautogui-with-selenium#pure-python).
